### ISSUE TITLE
BUG: map and name

### ISSUE THREAD

**Issue by CJ-Wright** [xpdAcq/SHED#54]
Nodes having names is a good thing, but currently the `name` kwargs gets passed inside the map function causing a lot of grief. Should we pop `name` off kwargs? This essentially means that `name` is never a valid kwarg for a map function, is this ok?

**Comment by CJ-Wright** [comment]
@ordirules @danielballan
Thoughts?

**Comment by ordirules** [comment]
sounds good, but I would call it something slightly less common, like `stream_name`

**Comment by CJ-Wright** [comment]
Fair, this will require a fix on the base library side too I'd imagine.

**Comment by danielballan** [comment]
You could also pass in kwargs as a dictionary, rather than as kwargs, to avoid name collisions.

**Comment by CJ-Wright** [comment]
I think this is addressed in #60 somewhat. I like the regular kwargs interface but we can change it if needed.

**Comment by CJ-Wright** [comment]
Closed by #60
